apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URI: "mongodb://root:<MONGO_PASSWORD>@<MONGODB_LOAD_BALANCER_IP>:27017/pipeline_monitor?authSource=admin"
  SESSION_SECRET: "supersecret"
  JWT_SECRET: "superjwtsecret"
  GITHUB_CLIENT_ID: "Ov23liRYNQPGaHkLyH94"
  GITHUB_CLIENT_SECRET: "a74cf05fe7d1dd80f89cb6afd38b04c4537dcbda"
  GITHUB_CALLBACK_URL: "http://<LOAD_BALANCER_IP>:5000/auth/github/callback"
  GITHUB_PAT: "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"
  GEMINI_API_KEY: "AIzaSyB1dNkYd-g2qFxWVTtk-FfaLjhWxUyB2Zw"
  GEMINI_MODEL: "gemini-2.5-flash"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: <you-registry>/pulse_back_end:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: backend-secrets
        env:
        - name: SWAGGER_SERVER_URL
          value: "http://<LOAD_BALANCER_IP>:5000"
